volumes:
  fga-data:
    name: fga-data

services:
  postgres:
    image: postgres:18-alpine
    container_name: fga_postgres
    command: postgres -c 'max_connections=100'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - fga-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: fga_migrate
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    command: migrate

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: fga_openfga
    command: run
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      OPENFGA_DATASTORE_MAX_OPEN_CONNS: "100" #see postgres container
      OPENFGA_EXPERIMENTALS: authzen
      OPENFGA_AUTHZEN_BASE_URL: http://localhost:8080
    ports:
      - "8080:8080" #http
      - "8081:8081" #grpc
      - "2112:2112" #prometheus metrics
    healthcheck:
      test:
        [ "CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081" ]
      interval: 5s
      timeout: 30s
      retries: 3
